
#Anti-Cheese is a system for managing how XP is gained.
#There are various ways in which players can exploit
#features of various mods and mechanics to gain xp at
#rates that are not intended.  The below anti-cheese
#features address many of the most common.
[AntiCheese]
	#if set to true, players who are AFK will continuously grow their
	#reduction value and will end up gaining negative xp.
	#If this is false, they only stop gaining and never lose.
	AFK_Can_Subtract = false

	#AFK Tracking allows you to control if and when a player
	#should not gain xp while afk.  All afk timers are configuration
	#specific, so you can configure separate thresholds for different
	#types of xp.
	[AntiCheese.AFK]

		[AntiCheese.AFK.SWIMMING]
			tolerance_flat = 0
			reduction = 0.1
			cooloff_amount = 1
			tolerance_percent = 0.0
			source = []
			min_time_to_apply = 200
			retention_duration = 0

		[AntiCheese.AFK.SWIM_SPRINTING]
			tolerance_flat = 0
			reduction = 0.1
			cooloff_amount = 1
			tolerance_percent = 0.0
			source = []
			min_time_to_apply = 200
			retention_duration = 0

		[AntiCheese.AFK.SURFACING]
			tolerance_flat = 0
			reduction = 0.1
			cooloff_amount = 1
			tolerance_percent = 0.0
			source = []
			min_time_to_apply = 200
			retention_duration = 0

		[AntiCheese.AFK.SUBMERGED]
			tolerance_flat = 0
			reduction = 0.1
			cooloff_amount = 1
			tolerance_percent = 0.0
			source = []
			min_time_to_apply = 200
			retention_duration = 0

		[AntiCheese.AFK.DIVING]
			tolerance_flat = 0
			reduction = 0.1
			cooloff_amount = 1
			tolerance_percent = 0.0
			source = []
			min_time_to_apply = 200
			retention_duration = 0

	#Diminishing XP allows you to reduce the amount of XP earned
	#for a specific event when the xp is earned in quick succession.
	[AntiCheese.DiminishingXP]

		[AntiCheese.DiminishingXP.RIDING]
			tolerance_flat = 0
			reduction = 0.05
			cooloff_amount = 0
			tolerance_percent = 0.0
			source = []
			min_time_to_apply = 0
			retention_duration = 200

		[AntiCheese.DiminishingXP.SPRINTING]
			tolerance_flat = 3
			reduction = 0.05
			cooloff_amount = 0
			tolerance_percent = 0.0
			source = []
			min_time_to_apply = 0
			retention_duration = 200

		[AntiCheese.DiminishingXP.SWIMMING]
			tolerance_flat = 0
			reduction = 0.05
			cooloff_amount = 0
			tolerance_percent = 0.0
			source = []
			min_time_to_apply = 0
			retention_duration = 200

		[AntiCheese.DiminishingXP.SURFACING]
			tolerance_flat = 0
			reduction = 0.99
			cooloff_amount = 0
			tolerance_percent = 0.0
			source = []
			min_time_to_apply = 0
			retention_duration = 200

		[AntiCheese.DiminishingXP.DIVING]
			tolerance_flat = 0
			reduction = 0.05
			cooloff_amount = 0
			tolerance_percent = 0.0
			source = []
			min_time_to_apply = 0
			retention_duration = 200

		[AntiCheese.DiminishingXP.SUBMERGED]
			tolerance_flat = 0
			reduction = 0.05
			cooloff_amount = 0
			tolerance_percent = 0.0
			source = []
			min_time_to_apply = 0
			retention_duration = 200

		[AntiCheese.DiminishingXP.SWIM_SPRINTING]
			tolerance_flat = 0
			reduction = 0.05
			cooloff_amount = 0
			tolerance_percent = 0.0
			source = []
			min_time_to_apply = 0
			retention_duration = 200

		[AntiCheese.DiminishingXP.BREATH_CHANGE]
			tolerance_flat = 0
			reduction = 0.05
			cooloff_amount = 0
			tolerance_percent = 0.0
			source = []
			min_time_to_apply = 0
			retention_duration = 200


		[AntiCheese.DiminishingXP.DEAL_MELEE_DAMAGE]
			tolerance_flat = 0
			reduction = 0.05
			cooloff_amount = 0
			tolerance_percent = 0.0
			source = []
			min_time_to_apply = 0
			retention_duration = 200
	#Normalization allows you to keep xp gain values from spiking
	#by keeping them within a range of tolerance.  When normalized,
	#xp from an event will not exceed the threshold above the previously
	#earned xp value.
	[AntiCheese.Normalization]

		[AntiCheese.Normalization.SPRINTING]
			tolerance_flat = 5
			reduction = 0.05
			cooloff_amount = 0
			tolerance_percent = 0.05
			source = []
			min_time_to_apply = 20
			retention_duration = 400

		[AntiCheese.Normalization.SWIMMING]
			tolerance_flat = 3
			reduction = 0.05
			cooloff_amount = 0
			tolerance_percent = 0.05
			source = []
			min_time_to_apply = 20
			retention_duration = 400

		[AntiCheese.Normalization.SURFACING]
			tolerance_flat = 1
			reduction = 1
			cooloff_amount = 0
			tolerance_percent = 0.05
			source = []
			min_time_to_apply = 20
			retention_duration = 400

		[AntiCheese.Normalization.DIVING]
			tolerance_flat = 1
			reduction = 1
			cooloff_amount = 0
			tolerance_percent = 0.05
			source = []
			min_time_to_apply = 20
			retention_duration = 400

		[AntiCheese.Normalization.SWIM_SPRINTING]
			tolerance_flat = 5
			reduction = 0.5
			cooloff_amount = 0
			tolerance_percent = 0.05
			source = []
			min_time_to_apply = 20
			retention_duration = 400

		[AntiCheese.Normalization.SUBMERGED]
			tolerance_flat = 5
			reduction = 1
			cooloff_amount = 0
			tolerance_percent = 0.05
			source = []
			min_time_to_apply = 20
			retention_duration = 400

		[AntiCheese.Normalization.FLYING]
			tolerance_flat = 5
			reduction = 0.5
			cooloff_amount = 0
			tolerance_percent = 0.05
			source = []
			min_time_to_apply = 20
			retention_duration = 400

		[AntiCheese.Normalization.BREATH_CHANGE]
			tolerance_flat = 1
			reduction = 1
			cooloff_amount = 0
			tolerance_percent = 0.05
			source = []
			min_time_to_apply = 20
			retention_duration = 400

